# Copyright 2026 N Vision Systems And Technologies SL
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
import shutil
from pathlib import Path

import nir as _nir
from snn_mlir._graph import parse_graph, quantize_layers
from snn_mlir.nodes import NodeInfo


def export(
    source: _nir.NIRGraph | str | Path,
    output_dir: str | Path,
    *,
    quantize: bool = False,
    n_steps: int = 100,
    index_bits: int = 64,
    input_file: str | Path | None = None,
) -> None:
    """Generate C runtime files (snn_data.h + main.c) for a NIR graph.

    Weights are baked into network.mlir as constant globals, so there is no
    snn_data.c — the header only carries layer-size macros.

    Intended to be called alongside snn_mlir.export() in example scripts.
    Not part of the pip-installable snn-mlir package.
    """
    if isinstance(source, (str, Path)):
        source = _nir.read(str(source))

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    layers = parse_graph(source)
    if quantize:
        quantize_layers(layers)

    first_synapse = next(layer for layer in layers if layer.is_synapse)
    last_neuron = next(layer for layer in reversed(layers) if layer.is_neuron)

    generate_snn_header(
        layers,
        input_size=first_synapse.weight_shape[1],
        output_size=last_neuron.state_size,
        n_steps=n_steps,
        output_path=output_path,
    )
    generate_main_c(
        layers,
        input_size=first_synapse.weight_shape[1],
        output_size=last_neuron.state_size,
        n_steps=n_steps,
        output_path=output_path,
        quantize=quantize,
        index_bits=index_bits,
    )

    if input_file is not None:
        shutil.copy2(input_file, output_path / "input.h")


def generate_snn_header(
    layers: list[NodeInfo],
    input_size: int,
    output_size: int,
    n_steps: int,
    output_path: Path,
) -> None:
    """Write snn_data.h — layer-size macros only (weights live in network.mlir)."""
    _write_header(layers, input_size, output_size, n_steps, output_path)


def generate_main_c(
    layers: list[NodeInfo],
    input_size: int,
    output_size: int,
    n_steps: int,
    output_path: Path,
    quantize: bool,
    index_bits: int = 64,
) -> None:
    """Write main.c test harness (timestep loop, memref descriptors)."""
    idx_t = f"int{index_bits}_t"
    L: list[str] = []

    L.append("/* Auto-generated by snn-mlir — do NOT edit */")
    L.append("#include <stdio.h>")
    L.append("#include <stdint.h>")
    L.append('#include "snn_data.h"')
    L.append('#include "input.h"')
    L.append("")

    # ── memref descriptor typedefs ────────────────────────────────────────────
    L.append(f"/* MLIR memref descriptors ({index_bits}-bit index) */")
    if quantize:
        L += _memref_typedef("Memref1Di8", "int8_t", 1, idx_t)
        L += _memref_typedef("Memref1Di32", "int32_t", 1, idx_t)
    else:
        L += _memref_typedef("Memref1Df32", "float", 1, idx_t)
    L.append("")

    # ── extern function declaration ───────────────────────────────────────────
    L += _extern_signature(layers, idx_t, quantize)
    L.append("")

    # ── helper constructors ───────────────────────────────────────────────────
    L += _mk_helpers(idx_t, quantize)
    L.append("")

    # ── main ──────────────────────────────────────────────────────────────────
    L.append("int main(void) {")

    last_neuron = next((layer for layer in reversed(layers) if layer.is_neuron), None)
    if quantize:
        if last_neuron and last_neuron.output_element_type(quantize) == "i32":
            out_t, out_desc_t, out_mk = "int32_t", "Memref1Di32", "mk1d_i32"
        else:
            out_t, out_desc_t, out_mk = "int8_t", "Memref1Di8", "mk1d_i8"
    else:
        out_t, out_desc_t, out_mk = "float", "Memref1Df32", "mk1d_f32"

    if not quantize:
        L.append("    float input_buf[INPUT_SIZE];")
    L.append(f"    {out_t} output_buf[OUTPUT_SIZE];")
    L.append("")

    # state arrays
    s_t = "int32_t" if quantize else "float"
    for layer in layers:
        if layer.is_neuron:
            for sname in layer.state_names:
                L.append(
                    f"    {s_t} {sname}_{layer.name}[{layer.state_size_define}] = {{0}};",
                )
    L.append("")

    # static descriptors
    if not quantize:
        L.append("    Memref1Df32 in_desc = mk1d_f32(input_buf, INPUT_SIZE);")
    L.append(f"    {out_desc_t} out_desc = {out_mk}(output_buf, OUTPUT_SIZE);")

    # Weights are baked into network.mlir as constant globals — no descriptors here.

    # state descriptors
    s_desc_t = "Memref1Di32" if quantize else "Memref1Df32"
    s_mk = "mk1d_i32" if quantize else "mk1d_f32"
    for layer in layers:
        if layer.is_neuron:
            for sname in layer.state_names:
                L.append(
                    f"    {s_desc_t} {sname[0]}{layer.name}_desc"
                    f" = {s_mk}({sname}_{layer.name}, {layer.state_size_define});",
                )
    L.append("")

    # timestep loop
    L.append('    printf("CSV_START\\n");')
    L.append(f"    for (int step = 0; step < {n_steps}; step++) {{")

    if quantize:
        L.append("        Memref1Di8 in_desc = mk1d_i8((int8_t *)L0_input[step], INPUT_SIZE);")
    else:
        L.append("        for (int i = 0; i < INPUT_SIZE; i++)")
        L.append("            input_buf[i] = (float)L0_input[step][i];")
    L.append("")

    # build call args
    call_args = ["&in_desc"]
    for layer in layers:
        if layer.is_neuron:
            for sname in layer.state_names:
                call_args.append(f"&{sname[0]}{layer.name}_desc")
    call_args.append("&out_desc")

    L.append("        _mlir_ciface_snn_forward_step(")
    L.append("            " + ", ".join(call_args) + ");")
    L.append("")

    # print output
    val_expr = "output_buf[i]" if quantize else "(int)output_buf[i]"
    L.append("        for (int i = 0; i < OUTPUT_SIZE; i++) {")
    L.append('            if (i > 0) printf(",");')
    L.append(f'            printf("%d", {val_expr});')
    L.append("        }")
    L.append('        printf("\\n");')

    L.append("    }")
    L.append('    printf("CSV_END\\n");')
    L.append("    return 0;")
    L.append("}")

    (output_path / "main.c").write_text("\n".join(L) + "\n")


# ── private helpers ────────────────────────────────────────────────────────────


def _memref_typedef(name: str, elem_t: str, rank: int, idx_t: str) -> list[str]:
    return [
        "typedef struct {",
        f"    {elem_t} *allocated;",
        f"    {elem_t} *aligned;",
        f"    {idx_t} offset;",
        f"    {idx_t} sizes[{rank}];",
        f"    {idx_t} strides[{rank}];",
        f"}} {name};",
    ]


def _extern_signature(layers: list[NodeInfo], idx_t: str, quantize: bool) -> list[str]:
    last_neuron = next((layer for layer in reversed(layers) if layer.is_neuron), None)
    if quantize:
        in_t, s_t = "Memref1Di8", "Memref1Di32"
        out_t = (
            "Memref1Di32"
            if (last_neuron and last_neuron.output_element_type(True) == "i32")
            else "Memref1Di8"
        )
    else:
        in_t, s_t = "Memref1Df32", "Memref1Df32"
        out_t = "Memref1Df32"

    # Weights are constant globals inside the module, not function arguments.
    args = [f"{in_t} *input"]
    for layer in layers:
        if layer.is_neuron:
            for sname in layer.state_names:
                args.append(f"{s_t} *{sname}_{layer.name}")
    args.append(f"{out_t} *output")

    return [
        "extern void _mlir_ciface_snn_forward_step(",
        "    " + ",\n    ".join(args),
        ");",
    ]


def _mk_helpers(idx_t: str, quantize: bool) -> list[str]:
    if quantize:
        return [
            f"static Memref1Di8 mk1d_i8(int8_t *p, {idx_t} n) {{",
            "    return (Memref1Di8){p, p, 0, {n}, {1}};",
            "}",
            f"static Memref1Di32 mk1d_i32(int32_t *p, {idx_t} n) {{",
            "    return (Memref1Di32){p, p, 0, {n}, {1}};",
            "}",
        ]
    return [
        f"static Memref1Df32 mk1d_f32(float *p, {idx_t} n) {{",
        "    return (Memref1Df32){p, p, 0, {n}, {1}};",
        "}",
    ]


def _write_header(
    layers: list[NodeInfo],
    input_size: int,
    output_size: int,
    n_steps: int,
    output_path: Path,
) -> None:
    lines = [
        "/* Auto-generated by snn-mlir — do NOT edit */",
        "#ifndef SNN_DATA_H",
        "#define SNN_DATA_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define N_STEPS      {n_steps}",
        f"#define INPUT_SIZE   {input_size}",
        f"#define OUTPUT_SIZE  {output_size}",
        "",
    ]
    for layer in layers:
        if layer.is_neuron:
            lines.append(f"#define {layer.state_size_define} {layer.state_size}")
    lines += [
        "",
        "/* Weights live as constant globals inside network.mlir, not here. */",
        "",
        "#endif /* SNN_DATA_H */",
    ]
    (output_path / "snn_data.h").write_text("\n".join(lines) + "\n")
