# Copyright 2026 N Vision Systems And Technologies SL
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
"""C runtime code generation for a NIR graph.

Turns a model folder (exactly one ``*.nir`` + an ``input.csv``) into a ``build/``
directory holding everything a compiler needs for the CPU reference:

    network.mlir   SNN-dialect MLIR (weights baked in as constant globals)
    snn_data.h     layer-size macros
    input.h        the input sequence, baked from input.csv (int8 L0_input)
    main.c         timestep-loop driver that prints one CSV row per step

``codegen_folder`` is the folder-level entry point the CLI drives; ``run`` (the
compile-and-execute verb) reuses it before invoking the toolchain.
"""

from pathlib import Path

import numpy as np

from ._api import export as export_mlir
from ._api import parse_graph, quantize_layers
from .nodes import NodeInfo


def codegen_folder(
    folder: "str | Path",
    *,
    quantize: bool = False,
    index_bits: int = 64,
) -> Path:
    """Emit ``<folder>/build/`` from a model folder.

    The folder must hold exactly one ``*.nir`` and an ``input.csv``. ``n_steps``
    is taken from the number of rows in ``input.csv``; its column count must
    match the network's input size.

    Returns the path to the generated ``build/`` directory.
    """
    folder = Path(folder)
    if not folder.is_dir():
        raise FileNotFoundError(f"folder not found: {folder}")

    nir_path = _find_single_nir(folder)
    csv_path = folder / "input.csv"
    if not csv_path.is_file():
        raise FileNotFoundError(f"input.csv not found in {folder}")

    layers = parse_graph(nir_path)
    if layers.recurrent_edges:
        # The MLIR emitter handles recurrence, but this C harness does not yet
        # pass the previous-spikes buffers the kernel then expects — generating
        # it anyway would compile a harness that calls the kernel with too few
        # arguments. Loud failure until the harness learns the extra arguments.
        raise NotImplementedError(
            "codegen for recurrent models is not supported yet "
            f"(recurrent edges: {layers.recurrent_edges})",
        )
    if quantize:
        quantize_layers(layers)

    first_synapse = next(layer for layer in layers if layer.is_synapse)
    last_neuron = next(layer for layer in reversed(layers) if layer.is_neuron)
    input_size = first_synapse.weight_shape[1]
    output_size = last_neuron.state_size

    build = folder / "build"
    build.mkdir(parents=True, exist_ok=True)

    n_steps = write_input_header(csv_path, build, expected_cols=input_size)
    export_mlir(nir_path, build / "network.mlir", quantize=quantize)
    generate_snn_header(layers, input_size, output_size, n_steps, build)
    generate_main_c(layers, input_size, output_size, n_steps, build, quantize, index_bits)
    return build


def _find_single_nir(folder: Path) -> Path:
    matches = sorted(folder.glob("*.nir"))
    if not matches:
        raise FileNotFoundError(f"no .nir file found in {folder}")
    if len(matches) > 1:
        names = ", ".join(p.name for p in matches)
        raise ValueError(f"multiple .nir files found in {folder} ({names}); expected exactly one")
    return matches[0]


def write_input_header(
    input_csv: "str | Path",
    output_dir: "str | Path",
    *,
    expected_cols: "int | None" = None,
) -> int:
    """Bake ``input.csv`` into ``output_dir/input.h`` (``int8_t L0_input[N][C]``).

    Returns the number of rows ``N`` (= ``n_steps``). Raises if the column count
    does not match ``expected_cols``.
    """
    arr = np.loadtxt(input_csv, delimiter=",", dtype=np.int64, ndmin=2)
    n_steps, n_cols = arr.shape
    if expected_cols is not None and n_cols != expected_cols:
        raise ValueError(
            f"{Path(input_csv).name} has {n_cols} columns but the network "
            f"expects {expected_cols} inputs"
        )

    lines = [
        "/* Auto-generated by snn-mlir — do NOT edit */",
        "#ifndef INPUT_H",
        "#define INPUT_H",
        "",
        "#include <stdint.h>",
        "",
        f"int8_t L0_input[{n_steps}][{n_cols}] = {{",
    ]
    for row in arr:
        lines.append("    {" + ",".join(str(int(v)) for v in row) + "},")
    lines += ["};", "", "#endif /* INPUT_H */"]
    Path(output_dir, "input.h").write_text("\n".join(lines) + "\n")
    return n_steps


def generate_snn_header(
    layers: list[NodeInfo],
    input_size: int,
    output_size: int,
    n_steps: int,
    output_path: Path,
) -> None:
    """Write snn_data.h — layer-size macros only (weights live in network.mlir)."""
    lines = [
        "/* Auto-generated by snn-mlir — do NOT edit */",
        "#ifndef SNN_DATA_H",
        "#define SNN_DATA_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define N_STEPS      {n_steps}",
        f"#define INPUT_SIZE   {input_size}",
        f"#define OUTPUT_SIZE  {output_size}",
        "",
    ]
    for layer in layers:
        if layer.is_neuron:
            lines.append(f"#define {layer.state_size_define} {layer.state_size}")
    lines += [
        "",
        "/* Weights live as constant globals inside network.mlir, not here. */",
        "",
        "#endif /* SNN_DATA_H */",
    ]
    (output_path / "snn_data.h").write_text("\n".join(lines) + "\n")


def generate_main_c(
    layers: list[NodeInfo],
    input_size: int,
    output_size: int,
    n_steps: int,
    output_path: Path,
    quantize: bool,
    index_bits: int = 64,
) -> None:
    """Write main.c test harness (timestep loop, memref descriptors)."""
    idx_t = f"int{index_bits}_t"
    L: list[str] = []

    L.append("/* Auto-generated by snn-mlir — do NOT edit */")
    L.append("#include <stdio.h>")
    L.append("#include <stdint.h>")
    L.append('#include "snn_data.h"')
    L.append('#include "input.h"')
    L.append("")

    # ── memref descriptor typedefs ────────────────────────────────────────────
    L.append(f"/* MLIR memref descriptors ({index_bits}-bit index) */")
    if quantize:
        L += _memref_typedef("Memref1Di8", "int8_t", 1, idx_t)
        L += _memref_typedef("Memref1Di32", "int32_t", 1, idx_t)
    else:
        L += _memref_typedef("Memref1Df32", "float", 1, idx_t)
    L.append("")

    # ── extern function declaration ───────────────────────────────────────────
    L += _extern_signature(layers, idx_t, quantize)
    L.append("")

    # ── helper constructors ───────────────────────────────────────────────────
    L += _mk_helpers(idx_t, quantize)
    L.append("")

    # ── main ──────────────────────────────────────────────────────────────────
    L.append("int main(void) {")

    last_neuron = next((layer for layer in reversed(layers) if layer.is_neuron), None)
    if quantize:
        if last_neuron and last_neuron.output_element_type(quantize) == "i32":
            out_t, out_desc_t, out_mk = "int32_t", "Memref1Di32", "mk1d_i32"
        else:
            out_t, out_desc_t, out_mk = "int8_t", "Memref1Di8", "mk1d_i8"
    else:
        out_t, out_desc_t, out_mk = "float", "Memref1Df32", "mk1d_f32"

    if not quantize:
        L.append("    float input_buf[INPUT_SIZE];")
    L.append(f"    {out_t} output_buf[OUTPUT_SIZE];")
    L.append("")

    # state arrays
    s_t = "int32_t" if quantize else "float"
    for layer in layers:
        if layer.is_neuron:
            for sname in layer.state_names:
                L.append(
                    f"    {s_t} {sname}_{layer.name}[{layer.state_size_define}] = {{0}};",
                )
    L.append("")

    # static descriptors
    if not quantize:
        L.append("    Memref1Df32 in_desc = mk1d_f32(input_buf, INPUT_SIZE);")
    L.append(f"    {out_desc_t} out_desc = {out_mk}(output_buf, OUTPUT_SIZE);")

    # Weights are baked into network.mlir as constant globals — no descriptors here.

    # state descriptors
    s_desc_t = "Memref1Di32" if quantize else "Memref1Df32"
    s_mk = "mk1d_i32" if quantize else "mk1d_f32"
    for layer in layers:
        if layer.is_neuron:
            for sname in layer.state_names:
                L.append(
                    f"    {s_desc_t} {sname[0]}{layer.name}_desc"
                    f" = {s_mk}({sname}_{layer.name}, {layer.state_size_define});",
                )
    L.append("")

    # timestep loop
    L.append('    printf("CSV_START\\n");')
    L.append(f"    for (int step = 0; step < {n_steps}; step++) {{")

    if quantize:
        L.append("        Memref1Di8 in_desc = mk1d_i8((int8_t *)L0_input[step], INPUT_SIZE);")
    else:
        L.append("        for (int i = 0; i < INPUT_SIZE; i++)")
        L.append("            input_buf[i] = (float)L0_input[step][i];")
    L.append("")

    # build call args
    call_args = ["&in_desc"]
    for layer in layers:
        if layer.is_neuron:
            for sname in layer.state_names:
                call_args.append(f"&{sname[0]}{layer.name}_desc")
    call_args.append("&out_desc")

    L.append("        _mlir_ciface_snn_forward_step(")
    L.append("            " + ", ".join(call_args) + ");")
    L.append("")

    # print output
    val_expr = "output_buf[i]" if quantize else "(int)output_buf[i]"
    L.append("        for (int i = 0; i < OUTPUT_SIZE; i++) {")
    L.append('            if (i > 0) printf(",");')
    L.append(f'            printf("%d", {val_expr});')
    L.append("        }")
    L.append('        printf("\\n");')

    L.append("    }")
    L.append('    printf("CSV_END\\n");')
    L.append("    return 0;")
    L.append("}")

    (output_path / "main.c").write_text("\n".join(L) + "\n")


# ── private helpers ────────────────────────────────────────────────────────────


def _memref_typedef(name: str, elem_t: str, rank: int, idx_t: str) -> list[str]:
    return [
        "typedef struct {",
        f"    {elem_t} *allocated;",
        f"    {elem_t} *aligned;",
        f"    {idx_t} offset;",
        f"    {idx_t} sizes[{rank}];",
        f"    {idx_t} strides[{rank}];",
        f"}} {name};",
    ]


def _extern_signature(layers: list[NodeInfo], idx_t: str, quantize: bool) -> list[str]:
    last_neuron = next((layer for layer in reversed(layers) if layer.is_neuron), None)
    if quantize:
        in_t, s_t = "Memref1Di8", "Memref1Di32"
        out_t = (
            "Memref1Di32"
            if (last_neuron and last_neuron.output_element_type(True) == "i32")
            else "Memref1Di8"
        )
    else:
        in_t, s_t = "Memref1Df32", "Memref1Df32"
        out_t = "Memref1Df32"

    # Weights are constant globals inside the module, not function arguments.
    args = [f"{in_t} *input"]
    for layer in layers:
        if layer.is_neuron:
            for sname in layer.state_names:
                args.append(f"{s_t} *{sname}_{layer.name}")
    args.append(f"{out_t} *output")

    return [
        "extern void _mlir_ciface_snn_forward_step(",
        "    " + ",\n    ".join(args),
        ");",
    ]


def _mk_helpers(idx_t: str, quantize: bool) -> list[str]:
    if quantize:
        return [
            f"static Memref1Di8 mk1d_i8(int8_t *p, {idx_t} n) {{",
            "    return (Memref1Di8){p, p, 0, {n}, {1}};",
            "}",
            f"static Memref1Di32 mk1d_i32(int32_t *p, {idx_t} n) {{",
            "    return (Memref1Di32){p, p, 0, {n}, {1}};",
            "}",
        ]
    return [
        f"static Memref1Df32 mk1d_f32(float *p, {idx_t} n) {{",
        "    return (Memref1Df32){p, p, 0, {n}, {1}};",
        "}",
    ]
